version: '3.8'

services:
  webrtc-karaoke:
    build: .
    ports:
      - "8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  https-proxy:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./init-ssl.sh:/init-ssl.sh:ro
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webrtc-karaoke
    restart: unless-stopped
    entrypoint: ["/init-ssl.sh"]